import { tv } from 'tailwind-variants';

export const triggerVariants = tv({
  base: [
    'au-select-trigger relative box-border cursor-pointer border-none',
    'transition duration-200 ease-in-out outline-[var(--grayscale-100)]',
    'dark:outline-[var(--grayscale-300)] rounded-lg text-sm font-medium decoration-0',
    'flex items-center text-center',
    'disabled:pointer-events-none',
    '[&>span]:leading-4 [&>span]:mt-0.5',
  ],
  variants: {
    theme: {
      primary: [
        'bg-[var(--primary-color)] text-[var(--white-color)]',
        'border border-solid border-[var(--primary-color)]',
        'hover:bg-[var(--primary-color-300)] hover:border-[var(--primary-color-300)]',
        'disabled:bg-[var(--grayscale-100)] dark:disabled:bg-[var(--grayscale-300)]',
        'disabled:border-[var(--grayscale-100)] dark:disabled:border-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-200)]',
      ],
      secondary: [
        'bg-[var(--secondary-color)] text-[var(--white-color)]',
        'border border-solid border-[var(--secondary-color)]',
        'hover:bg-[var(--secondary-color-200)] hover:border-[var(--secondary-color-200)]',
        'disabled:bg-[var(--grayscale-100)] dark:disabled:bg-[var(--grayscale-300)]',
        'disabled:border-[var(--grayscale-100)] dark:disabled:border-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-200)]',
      ],
      tertiary1: [
        'bg-[var(--tertiary-color-1)] text-[var(--white-color)]',
        'border border-solid border-[var(--tertiary-color-1)]',
        'hover:opacity-80',
        'disabled:bg-[var(--grayscale-100)] dark:disabled:bg-[var(--grayscale-300)]',
        'disabled:border-[var(--grayscale-100)] dark:disabled:border-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-200)]',
      ],
      tertiary2: [
        'bg-[var(--tertiary-color-2)] text-[var(--white-color)]',
        'border border-solid border-[var(--tertiary-color-2)]',
        'hover:opacity-80',
        'disabled:bg-[var(--grayscale-100)] dark:disabled:bg-[var(--grayscale-300)]',
        'disabled:border-[var(--grayscale-100)] dark:disabled:border-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-200)]',
      ],
      tertiary3: [
        'bg-[var(--tertiary-color-3)] text-[var(--white-color)]',
        'border border-solid border-[var(--tertiary-color-3)]',
        'hover:opacity-80',
        'disabled:bg-[var(--grayscale-100)] dark:disabled:bg-[var(--grayscale-300)]',
        'disabled:border-[var(--grayscale-100)] dark:disabled:border-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-200)]',
      ],
      supportPastel2: [
        'bg-[var(--support-pastel-color-2)] text-[var(--white-color)]',
        'border border-solid border-[var(--support-pastel-color-2)]',
        'hover:opacity-80',
        'disabled:bg-[var(--grayscale-100)] dark:disabled:bg-[var(--grayscale-300)]',
        'disabled:border-[var(--grayscale-100)] dark:disabled:border-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-200)]',
      ],
      gray: [
        'bg-[var(--gray-color)] text-[var(--grayscale-200)]',
        'dark:bg-[var(--grayscale-400)] dark:text-[var(--grayscale-100)]',
        'border border-solid border-[var(--gray-color)] dark:border-[var(--grayscale-400)]',
        'hover:bg-[var(--grayscale-100)] dark:hover:bg-[var(--grayscale-300)]',
        'hover:border-[var(--grayscale-100)] dark:hover:border-[var(--grayscale-300)]',
        'disabled:bg-[var(--grayscale-100)] dark:disabled:bg-[var(--grayscale-300)]',
        'disabled:border-[var(--grayscale-100)] dark:disabled:border-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-200)]',
      ],
      success: [
        'bg-[var(--success-color)] text-[var(--white-color)]',
        'border border-solid border-[var(--success-color)]',
        'hover:bg-[var(--success-color-300)] hover:border-[var(--success-color-300)]',
        'disabled:bg-[var(--grayscale-100)] dark:disabled:bg-[var(--grayscale-300)]',
        'disabled:border-[var(--grayscale-100)] dark:disabled:border-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-200)]',
      ],
      danger: [
        'bg-[var(--danger-color)] text-[var(--white-color)]',
        'border border-solid border-[var(--danger-color)]',
        'hover:bg-[var(--danger-color-300)] hover:border-[var(--danger-color-300)]',
        'disabled:bg-[var(--grayscale-100)] dark:disabled:bg-[var(--grayscale-300)]',
        'disabled:border-[var(--grayscale-100)] dark:disabled:border-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-200)]',
      ],
      warning: [
        'bg-[var(--warning-color)] text-[var(--grayscale-400)]',
        'border border-solid border-[var(--warning-color)]',
        'hover:bg-[var(--warning-color-100)] hover:border-[var(--warning-color-100)]',
        'disabled:bg-[var(--grayscale-100)] dark:disabled:bg-[var(--grayscale-300)]',
        'disabled:border-[var(--grayscale-100)] dark:disabled:border-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-200)]',
      ],
      dark: [
        'bg-[var(--dark-color)] text-[var(--white-color)]',
        'dark:bg-[var(--white-color)] dark:text-[var(--dark-color)]',
        'hover:bg-[var(--grayscale-400)] dark:hover:bg-[var(--grayscale-100)]',
        'border border-solid border-[var(--dark-color)] hover:border-[var(--grayscale-400)]',
        'dark:border-[var(--white-color)]',
        'disabled:bg-[var(--grayscale-100)] dark:disabled:bg-[var(--grayscale-300)]',
        'disabled:border-[var(--grayscale-100)] dark:disabled:border-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-200)] dark:disabled:text-[var(--grayscale-200)]',
      ],
      white: [
        'bg-[var(--white-color)] text-[var(--dark-color)]',
        'dark:bg-[var(--dark-color)] dark:text-[var(--white-color)]',
        'hover:bg-[var(--grayscale-100)] dark:hover:bg-[var(--grayscale-400)]',
        'border border-solid border-[var(--white-color)] hover:border-[var(--grayscale-100)]',
        'dark:border-[var(--dark-color)] dark:hover:border-[var(--grayscale-400)]',
        'disabled:bg-[var(--grayscale-100)] dark:disabled:bg-[var(--grayscale-300)]',
        'disabled:border-[var(--grayscale-100)] dark:disabled:border-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-200)] dark:disabled:text-[var(--grayscale-200)]',
      ],

      linkPrimary: [
        'bg-none text-[var(--primary-color)]',
        'hover:text-[var(--primary-color-300)]',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
        'outline-0',
      ],
      linkSecondary: [
        'bg-none text-[var(--secondary-color)]',
        'hover:text-[var(--secondary-color-200)]',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
        'outline-0',
      ],
      linkTertiary1: [
        'bg-none text-[var(--tertiary-color-1)]',
        'hover:opacity-80',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
        'outline-0',
      ],
      linkTertiary2: [
        'bg-none text-[var(--tertiary-color-2)]',
        'hover:opacity-80',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
        'outline-0',
      ],
      linkTertiary3: [
        'bg-none text-[var(--tertiary-color-3)]',
        'hover:opacity-80',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
        'outline-0',
      ],
      linkSupportPastel2: [
        'bg-none text-[var(--support-pastel-color-2)]',
        'hover:opacity-80',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
        'outline-0',
      ],
      linkGray: [
        'bg-none text-[var(--grayscale-200)]',
        'hover:text-[var(--grayscale-400)] dark:hover:text-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
        'outline-0',
      ],
      linkSuccess: [
        'bg-none text-[var(--success-color)]',
        'hover:text-[var(--success-color-300)]',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
        'outline-0',
      ],
      linkDanger: [
        'bg-none text-[var(--danger-color)]',
        'hover:text-[var(--danger-color-300)]',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
        'outline-0',
      ],
      linkWarning: [
        'bg-none text-[var(--warning-color)]',
        'hover:text-[var(--warning-color-100)]',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
        'outline-0',
      ],
      linkDark: [
        'bg-none text-[var(--dark-color)]',
        'hover:text-[var(--grayscale-300)]',
        'dark:text-[var(--white-color)] dark:hover:text-[var(--grayscale-200)]',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
        'outline-0',
      ],
      linkWhite: [
        'bg-none text-[var(--white-color)]',
        'hover:text-[var(--grayscale-100)]',
        'dark:text-[var(--dark-color)] dark:hover:text-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
        'outline-0',
      ],

      primaryFlat: [
        'bg-none text-[var(--primary-color)] border border-solid border-transparent',
        'hover:bg-[var(--gray-color)] dark:hover:bg-[var(--grayscale-400)]',
        'hover:border-[var(--gray-color)] dark:hover:border-[var(--grayscale-400)]',
        'active:bg-[var(--primary-color)] active:text-[var(--white-color)] active:border-[var(--primary-color)]',
        'dark:active:bg-[var(--primary-color)] dark:active:text-[var(--white-color)] dark:active:border-[var(--primary-color)]',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
      ],
      secondaryFlat: [
        'bg-none text-[var(--secondary-color-200)] border border-solid border-transparent',
        'hover:bg-[var(--gray-color)] dark:hover:bg-[var(--grayscale-400)]',
        'hover:border-[var(--gray-color)] dark:hover:border-[var(--grayscale-400)]',
        'active:bg-[var(--secondary-color-200)] active:text-[var(--white-color)] active:border-[var(--secondary-color-200)]',
        'dark:active:bg-[var(--secondary-color-200)] dark:active:text-[var(--white-color)] dark:active:border-[var(--secondary-color-200)]',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
      ],
      tertiaryFlat1: [
        'bg-none text-[var(--tertiary-color-1)] border border-solid border-transparent',
        'hover:bg-[var(--gray-color)] dark:hover:bg-[var(--grayscale-400)]',
        'hover:border-[var(--gray-color)] dark:hover:border-[var(--grayscale-400)]',
        'active:bg-[var(--tertiary-color-1)] active:text-[var(--white-color)] active:border-[var(--tertiary-color-1)]',
        'dark:active:bg-[var(--tertiary-color-1)] dark:active:text-[var(--white-color)] dark:active:border-[var(--tertiary-color-1)]',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
      ],
      tertiaryFlat2: [
        'bg-none text-[var(--tertiary-color-2)] border border-solid border-transparent',
        'hover:bg-[var(--gray-color)] dark:hover:bg-[var(--grayscale-400)]',
        'hover:border-[var(--gray-color)] dark:hover:border-[var(--grayscale-400)]',
        'active:bg-[var(--tertiary-color-2)] active:text-[var(--white-color)] active:border-[var(--tertiary-color-2)]',
        'dark:active:bg-[var(--tertiary-color-2)] dark:active:text-[var(--white-color)] dark:active:border-[var(--tertiary-color-2)]',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
      ],
      tertiaryFlat3: [
        'bg-none text-[var(--tertiary-color-3)] border border-solid border-transparent',
        'hover:bg-[var(--gray-color)] dark:hover:bg-[var(--grayscale-400)]',
        'hover:border-[var(--gray-color)] dark:hover:border-[var(--grayscale-400)]',
        'active:bg-[var(--tertiary-color-3)] active:text-[var(--white-color)] active:border-[var(--tertiary-color-3)]',
        'dark:active:bg-[var(--tertiary-color-3)] dark:active:text-[var(--white-color)] dark:active:border-[var(--tertiary-color-3)]',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
      ],
      supportPastelFlat2: [
        'bg-none text-[var(--support-pastel-color-2)] border border-solid border-transparent',
        'hover:bg-[var(--gray-color)] dark:hover:bg-[var(--grayscale-400)]',
        'hover:border-[var(--gray-color)] dark:hover:border-[var(--grayscale-400)]',
        'active:bg-[var(--support-pastel-color-2)] active:text-[var(--white-color)] active:border-[var(--support-pastel-color-2)]',
        'dark:active:bg-[var(--support-pastel-color-2)] dark:active:text-[var(--white-color)] dark:active:border-[var(--support-pastel-color-2)]',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
      ],
      grayFlat: [
        'bg-none text-[var(--grayscale-200)] border border-solid border-transparent',
        'hover:bg-[var(--gray-color)] dark:hover:bg-[var(--grayscale-400)]',
        'hover:border-[var(--gray-color)] dark:hover:border-[var(--grayscale-400)]',
        'active:bg-[var(--grayscale-200)] active:text-[var(--white-color)] active:border-[var(--grayscale-200)]',
        'dark:active:bg-[var(--grayscale-200)] dark:active:text-[var(--white-color)] dark:active:border-[var(--grayscale-200)]',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
      ],
      successFlat: [
        'bg-none text-[var(--success-color)] border border-solid border-transparent',
        'hover:bg-[var(--gray-color)] dark:hover:bg-[var(--grayscale-400)]',
        'hover:border-[var(--gray-color)] dark:hover:border-[var(--grayscale-400)]',
        'active:bg-[var(--success-color)] active:text-[var(--white-color)] active:border-[var(--success-color)]',
        'dark:active:bg-[var(--success-color)] dark:active:text-[var(--white-color)] dark:active:border-[var(--success-color)]',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
      ],
      dangerFlat: [
        'bg-none text-[var(--danger-color)] border border-solid border-transparent',
        'hover:bg-[var(--gray-color)] dark:hover:bg-[var(--grayscale-400)]',
        'hover:border-[var(--gray-color)] dark:hover:border-[var(--grayscale-400)]',
        'active:bg-[var(--danger-color)] active:text-[var(--white-color)] active:border-[var(--danger-color)]',
        'dark:active:bg-[var(--danger-color)] dark:active:text-[var(--white-color)] dark:active:border-[var(--danger-color)]',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
      ],
      warningFlat: [
        'bg-none text-[var(--warning-color)] border border-solid border-transparent',
        'hover:bg-[var(--gray-color)] dark:hover:bg-[var(--grayscale-400)]',
        'hover:border-[var(--gray-color)] dark:hover:border-[var(--grayscale-400)]',
        'active:bg-[var(--warning-color)] active:text-[var(--white-color)] active:border-[var(--warning-color)]',
        'dark:active:bg-[var(--warning-color)] dark:active:text-[var(--white-color)] dark:active:border-[var(--warning-color)]',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
      ],
      darkFlat: [
        'bg-none text-[var(--dark-color)] dark:text-[var(--white-color)] border border-solid border-transparent',
        'hover:bg-[var(--gray-color)] dark:hover:bg-[var(--grayscale-400)]',
        'hover:border-[var(--gray-color)] dark:hover:border-[var(--grayscale-400)]',
        'active:bg-[var(--dark-color)] active:text-[var(--white-color)]',
        'dark:active:bg-[var(--white-color)] dark:active:text-[var(--dark-color)]',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
      ],
      whiteFlat: [
        'bg-none text-[var(--white-color)] dark:text-[var(--dark-color)] border border-solid border-transparent',
        'hover:bg-[var(--gray-color)] dark:hover:bg-[var(--grayscale-400)]',
        'hover:border-[var(--gray-color)] dark:hover:border-[var(--grayscale-400)]',
        'active:bg-[var(--white-color)] active:text-[var(--dark-color)]',
        'dark:active:bg-[var(--dark-color)] dark:active:text-[var(--white-color)]',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
      ],

      outlinePrimary: [
        'bg-none text-[var(--primary-color)]',
        'border border-solid border-[var(--grayscale-100)] dark:border-[var(--grayscale-300)]',
        'hover:border-[var(--primary-color)] dark:hover:border-[var(--primary-color)]',
        'active:bg-[var(--primary-color)] active:text-[var(--white-color)]',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
      ],
      outlineSecondary: [
        'bg-none text-[var(--secondary-color)]',
        'border border-solid border-[var(--grayscale-100)] dark:border-[var(--grayscale-300)]',
        'hover:border-[var(--secondary-color)] dark:hover:border-[var(--secondary-color)]',
        'active:bg-[var(--secondary-color)] active:text-[var(--white-color)]',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
      ],
      outlineTertiary1: [
        'bg-none text-[var(--tertiary-color-1)]',
        'border border-solid border-[var(--grayscale-100)] dark:border-[var(--grayscale-300)]',
        'hover:border-[var(--tertiary-color-1)] dark:hover:border-[var(--tertiary-color-1)]',
        'active:bg-[var(--tertiary-color-1)] active:text-[var(--white-color)]',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
      ],
      outlineTertiary2: [
        'bg-none text-[var(--tertiary-color-2)]',
        'border border-solid border-[var(--grayscale-100)] dark:border-[var(--grayscale-300)]',
        'hover:border-[var(--tertiary-color-2)] dark:hover:border-[var(--tertiary-color-2)]',
        'active:bg-[var(--tertiary-color-2)] active:text-[var(--white-color)]',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
      ],
      outlineTertiary3: [
        'bg-none text-[var(--tertiary-color-3)]',
        'border border-solid border-[var(--grayscale-100)] dark:border-[var(--grayscale-300)]',
        'hover:border-[var(--tertiary-color-3)] dark:hover:border-[var(--tertiary-color-3)]',
        'active:bg-[var(--tertiary-color-3)] active:text-[var(--white-color)]',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
      ],
      outlineSupportPastel2: [
        'bg-none text-[var(--support-pastel-color-2)]',
        'border border-solid border-[var(--grayscale-100)] dark:border-[var(--grayscale-300)]',
        'hover:border-[var(--support-pastel-color-2)] dark:hover:border-[var(--support-pastel-color-2)]',
        'active:bg-[var(--support-pastel-color-2)] active:text-[var(--white-color)]',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
      ],
      outlineGray: [
        'bg-none text-[var(--grayscale-200)]',
        'border border-solid border-[var(--grayscale-100)] dark:border-[var(--grayscale-300)]',
        'hover:border-[var(--grayscale-200)] dark:hover:border-[var(--grayscale-200)]',
        'active:bg-[var(--grayscale-200)] active:text-[var(--white-color)]',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
      ],
      outlineSuccess: [
        'bg-none text-[var(--success-color)]',
        'border border-solid border-[var(--grayscale-100)] dark:border-[var(--grayscale-300)]',
        'hover:border-[var(--success-color)] dark:hover:border-[var(--success-color)]',
        'active:bg-[var(--success-color)] active:text-[var(--white-color)]',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
      ],
      outlineDanger: [
        'bg-none text-[var(--danger-color)]',
        'border border-solid border-[var(--grayscale-100)] dark:border-[var(--grayscale-300)]',
        'hover:border-[var(--danger-color)] dark:hover:border-[var(--danger-color)]',
        'active:bg-[var(--danger-color)] active:text-[var(--white-color)]',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
      ],
      outlineWarning: [
        'bg-none text-[var(--warning-color)]',
        'border border-solid border-[var(--grayscale-100)] dark:border-[var(--grayscale-300)]',
        'hover:border-[var(--warning-color)] dark:hover:border-[var(--warning-color)]',
        'active:bg-[var(--warning-color)] active:text-[var(--white-color)]',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
      ],
      outlineDark: [
        'bg-none text-[var(--dark-color)] dark:text-[var(--white-color)]',
        'border border-solid border-[var(--grayscale-100)] dark:border-[var(--grayscale-300)]',
        'hover:border-[var(--dark-color)] dark:hover:border-[var(--white-color)]',
        'active:bg-[var(--dark-color)] active:text-[var(--white-color)] dark:active:bg-[var(--white-color)] dark:active:text-[var(--dark-color)]',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
      ],
      outlineWhite: [
        'bg-none text-[var(--white-color)] dark:text-[var(--dark-color)]',
        'border border-solid border-[var(--grayscale-100)] dark:border-[var(--grayscale-300)]',
        'hover:border-[var(--white-color)] dark:hover:border-[var(--dark-color)]',
        'active:bg-[var(--white-color)] active:text-[var(--dark-color)] dark:active:bg-[var(--dark-color)] dark:active:text-[var(--white-color)]',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
      ],

      grayPrimary: [
        'bg-none text-[var(--primary-color)]',
        'bg-[var(--gray-color)] dark:bg-[var(--grayscale-400)]',
        'hover:bg-[var(--primary-color)] hover:text-[var(--white-color)]',
        'border border-solid border-[var(--gray-color)] hover:border-[var(--primary-color)]',
        'active:bg-[var(--primary-color-300)] active:text-[var(--white-color)]',
        'dark:hover:bg-[var(--primary-color)] dark:hover:text-[var(--white-color)]',
        'dark:active:bg-[var(--primary-color-300)] dark:active:text-[var(--white-color)]',
        'dark:border-[var(--grayscale-400)] dark:hover:border-[var(--primary-color)]',
        'disabled:border-[var(--grayscale-100)] dark:disabled:border-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-200)] disabled:bg-[var(--grayscale-100)] dark:disabled:bg-[var(--grayscale-300)]',
      ],
      graySecondary: [
        'bg-none text-[var(--secondary-color)]',
        'bg-[var(--gray-color)] dark:bg-[var(--grayscale-400)]',
        'hover:bg-[var(--secondary-color)] hover:text-[var(--white-color)]',
        'border border-solid border-[var(--gray-color)] hover:border-[var(--secondary-color)]',
        'active:bg-[var(--secondary-color-200)] active:text-[var(--white-color)]',
        'dark:hover:bg-[var(--secondary-color)] dark:hover:text-[var(--white-color)]',
        'dark:active:bg-[var(--secondary-color-200)] dark:active:text-[var(--white-color)]',
        'dark:border-[var(--grayscale-400)] dark:hover:border-[var(--secondary-color)]',
        'disabled:border-[var(--grayscale-100)] dark:disabled:border-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-200)] disabled:bg-[var(--grayscale-100)] dark:disabled:bg-[var(--grayscale-300)]',
      ],
      grayTertiary1: [
        'bg-none text-[var(--tertiary-color-1)]',
        'bg-[var(--gray-color)] dark:bg-[var(--grayscale-400)]',
        'hover:bg-[var(--tertiary-color-1)] hover:text-[var(--white-color)]',
        'border border-solid border-[var(--gray-color)] hover:border-[var(--tertiary-color-1)]',
        'active:bg-[var(--tertiary-color-1)] active:text-[var(--white-color)]',
        'dark:hover:bg-[var(--tertiary-color-1)] dark:hover:text-[var(--white-color)]',
        'dark:active:bg-[var(--tertiary-color-1)] dark:active:text-[var(--white-color)]',
        'dark:border-[var(--grayscale-400)] dark:hover:border-[var(--tertiary-color-1)]',
        'disabled:border-[var(--grayscale-100)] dark:disabled:border-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-200)] disabled:bg-[var(--grayscale-100)] dark:disabled:bg-[var(--grayscale-300)]',
      ],
      grayTertiary2: [
        'bg-none text-[var(--tertiary-color-2)]',
        'bg-[var(--gray-color)] dark:bg-[var(--grayscale-400)]',
        'hover:bg-[var(--tertiary-color-2)] hover:text-[var(--white-color)]',
        'border border-solid border-[var(--gray-color)] hover:border-[var(--tertiary-color-2)]',
        'active:bg-[var(--tertiary-color-2)] active:text-[var(--white-color)]',
        'dark:hover:bg-[var(--tertiary-color-2)] dark:hover:text-[var(--white-color)]',
        'dark:active:bg-[var(--tertiary-color-2)] dark:active:text-[var(--white-color)]',
        'dark:border-[var(--grayscale-400)] dark:hover:border-[var(--tertiary-color-2)]',
        'disabled:border-[var(--grayscale-100)] dark:disabled:border-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-200)] disabled:bg-[var(--grayscale-100)] dark:disabled:bg-[var(--grayscale-300)]',
      ],
      grayTertiary3: [
        'bg-none text-[var(--tertiary-color-3)]',
        'bg-[var(--gray-color)] dark:bg-[var(--grayscale-400)]',
        'hover:bg-[var(--tertiary-color-3)] hover:text-[var(--white-color)]',
        'border border-solid border-[var(--gray-color)] hover:border-[var(--tertiary-color-3)]',
        'active:bg-[var(--tertiary-color-3)] active:text-[var(--white-color)]',
        'dark:hover:bg-[var(--tertiary-color-3)] dark:hover:text-[var(--white-color)]',
        'dark:active:bg-[var(--tertiary-color-3)] dark:active:text-[var(--white-color)]',
        'dark:border-[var(--grayscale-400)] dark:hover:border-[var(--tertiary-color-3)]',
        'disabled:border-[var(--grayscale-100)] dark:disabled:border-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-200)] disabled:bg-[var(--grayscale-100)] dark:disabled:bg-[var(--grayscale-300)]',
      ],
      graySupportPastel2: [
        'bg-none text-[var(--support-pastel-color-2)]',
        'bg-[var(--gray-color)] dark:bg-[var(--grayscale-400)]',
        'hover:bg-[var(--support-pastel-color-2)] hover:text-[var(--white-color)]',
        'border border-solid border-[var(--gray-color)] hover:border-[var(--support-pastel-color-2)]',
        'active:bg-[var(--support-pastel-color-2)] active:text-[var(--white-color)]',
        'dark:hover:bg-[var(--support-pastel-color-2)] dark:hover:text-[var(--white-color)]',
        'dark:active:bg-[var(--support-pastel-color-2)] dark:active:text-[var(--white-color)]',
        'dark:border-[var(--grayscale-400)] dark:hover:border-[var(--support-pastel-color-2)]',
        'disabled:border-[var(--grayscale-100)] dark:disabled:border-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-200)] disabled:bg-[var(--grayscale-100)] dark:disabled:bg-[var(--grayscale-300)]',
      ],
      graySuccess: [
        'bg-none text-[var(--success-color)]',
        'bg-[var(--gray-color)] dark:bg-[var(--grayscale-400)]',
        'hover:bg-[var(--success-color)] hover:text-[var(--white-color)]',
        'border border-solid border-[var(--gray-color)] hover:border-[var(--success-color)]',
        'active:bg-[var(--success-color-300)] active:text-[var(--white-color)]',
        'dark:hover:bg-[var(--success-color)] dark:hover:text-[var(--white-color)]',
        'dark:active:bg-[var(--success-color-300)] dark:active:text-[var(--white-color)]',
        'dark:border-[var(--grayscale-400)] dark:hover:border-[var(--success-color)]',
        'disabled:border-[var(--grayscale-100)] dark:disabled:border-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-200)] disabled:bg-[var(--grayscale-100)] dark:disabled:bg-[var(--grayscale-300)]',
      ],
      grayDanger: [
        'bg-none text-[var(--danger-color)]',
        'bg-[var(--gray-color)] dark:bg-[var(--grayscale-400)]',
        'hover:bg-[var(--danger-color)] hover:text-[var(--white-color)]',
        'border border-solid border-[var(--gray-color)] hover:border-[var(--danger-color)]',
        'active:bg-[var(--danger-color-300)] active:text-[var(--white-color)]',
        'dark:hover:bg-[var(--danger-color)] dark:hover:text-[var(--white-color)]',
        'dark:active:bg-[var(--danger-color-300)] dark:active:text-[var(--white-color)]',
        'dark:border-[var(--grayscale-400)] dark:hover:border-[var(--danger-color)]',
        'disabled:border-[var(--grayscale-100)] dark:disabled:border-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-200)] disabled:bg-[var(--grayscale-100)] dark:disabled:bg-[var(--grayscale-300)]',
      ],
      grayWarning: [
        'bg-none text-[var(--warning-color)]',
        'bg-[var(--gray-color)] dark:bg-[var(--grayscale-400)]',
        'hover:bg-[var(--warning-color)] hover:text-[var(--white-color)]',
        'border border-solid border-[var(--gray-color)] hover:border-[var(--warning-color)]',
        'active:bg-[var(--warning-color)] active:text-[var(--white-color)]',
        'dark:hover:bg-[var(--warning-color)] dark:hover:text-[var(--white-color)]',
        'dark:active:bg-[var(--warning-color)] dark:active:text-[var(--white-color)]',
        'dark:border-[var(--grayscale-400)] dark:hover:border-[var(--warning-color)]',
        'disabled:border-[var(--grayscale-100)] dark:disabled:border-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-200)] disabled:bg-[var(--grayscale-100)] dark:disabled:bg-[var(--grayscale-300)]',
      ],
      grayDark: [
        'bg-none text-[var(--dark-color)]',
        'bg-[var(--gray-color)] dark:bg-[var(--grayscale-400)]',
        'hover:bg-[var(--dark-color)] hover:text-[var(--white-color)]',
        'border border-solid border-[var(--gray-color)] hover:border-[var(--dark-color)]',
        'active:bg-[var(--grayscale-400)] active:text-[var(--white-color)]',
        'dark:text-[var(--white-color)]',
        'dark:hover:bg-[var(--white-color)] dark:hover:text-[var(--dark-color)]',
        'dark:active:bg-[var(--grayscale-100)] dark:active:text-[var(--dark-color)]',
        'dark:border-[var(--grayscale-400)] dark:hover:border-[var(--white-color)]',
        'disabled:border-[var(--grayscale-100)] dark:disabled:border-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-200)] disabled:bg-[var(--grayscale-100)] dark:disabled:bg-[var(--grayscale-300)]',
        'dark:disabled:text-[var(--grayscale-200)]',
      ],
      grayWhite: [
        'bg-none text-[var(--white-color)]',
        'bg-[var(--gray-color)] dark:bg-[var(--grayscale-400)]',
        'hover:bg-[var(--white-color)] hover:text-[var(--dark-color)]',
        'border border-solid border-[var(--gray-color)] hover:border-[var(--white-color)]',
        'active:bg-[var(--gray-color)] active:text-[var(--white-color)]',
        'dark:text-[var(--dark-color)]',
        'dark:hover:bg-[var(--dark-color)] dark:hover:text-[var(--white-color)]',
        'dark:active:bg-[var(--grayscale-400)] dark:active:text-[var(--white-color)]',
        'dark:border-[var(--grayscale-400)] dark:hover:border-[var(--dark-color)]',
        'disabled:border-[var(--grayscale-100)] dark:disabled:border-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-200)] disabled:bg-[var(--grayscale-100)] dark:disabled:bg-[var(--grayscale-300)]',
        'dark:disabled:text-[var(--grayscale-200)]',
      ],

      primaryShadow: [
        'border border-solid border-[var(--white-color)] dark:border-[var(--grayscale-400)]',
        'bg-[var(--white-color)] dark:bg-[var(--grayscale-400)]',
        'text-[var(--primary-color)]',
        'shadow-md shadow-[var(--grayscale-200)] dark:shadow-[var(--grayscale-300)]',
        'hover:shadow-none hover:border-[var(--primary-color)] dark:hover:border-[var(--primary-color)]',
        'active:bg-[var(--primary-color)] active:text-[var(--white-color)] dark:active:bg-[var(--primary-color)]',
        'disabled:border-[var(--grayscale-100)] dark:disabled:border-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-200)] disabled:bg-[var(--grayscale-100)]',
        'dark:disabled:bg-[var(--grayscale-300)] dark:disabled:text-[var(--grayscale-200)]',
        'disabled:shadow-none',
      ],
      secondaryShadow: [
        'border border-solid border-[var(--white-color)] dark:border-[var(--grayscale-400)]',
        'bg-[var(--white-color)] dark:bg-[var(--grayscale-400)]',
        'text-[var(--secondary-color)]',
        'shadow-md shadow-[var(--grayscale-200)] dark:shadow-[var(--grayscale-300)]',
        'hover:shadow-none hover:border-[var(--secondary-color)] dark:hover:border-[var(--secondary-color)]',
        'active:bg-[var(--secondary-color)] active:text-[var(--white-color)] dark:active:bg-[var(--secondary-color)]',
        'disabled:border-[var(--grayscale-100)] dark:disabled:border-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-200)] disabled:bg-[var(--grayscale-100)]',
        'dark:disabled:bg-[var(--grayscale-300)] dark:disabled:text-[var(--grayscale-200)]',
        'disabled:shadow-none',
      ],
      tertiaryShadow1: [
        'border border-solid border-[var(--white-color)] dark:border-[var(--grayscale-400)]',
        'bg-[var(--white-color)] dark:bg-[var(--grayscale-400)]',
        'text-[var(--tertiary-color-1)]',
        'shadow-md shadow-[var(--grayscale-200)] dark:shadow-[var(--grayscale-300)]',
        'hover:shadow-none hover:border-[var(--tertiary-color-1)] dark:hover:border-[var(--tertiary-color-1)]',
        'active:bg-[var(--tertiary-color-1)] active:text-[var(--white-color)] dark:active:bg-[var(--tertiary-color-1)]',
        'disabled:border-[var(--grayscale-100)] dark:disabled:border-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-200)] disabled:bg-[var(--grayscale-100)]',
        'dark:disabled:bg-[var(--grayscale-300)] dark:disabled:text-[var(--grayscale-200)]',
        'disabled:shadow-none',
      ],
      tertiaryShadow2: [
        'border border-solid border-[var(--white-color)] dark:border-[var(--grayscale-400)]',
        'bg-[var(--white-color)] dark:bg-[var(--grayscale-400)]',
        'text-[var(--tertiary-color-2)]',
        'shadow-md shadow-[var(--grayscale-200)] dark:shadow-[var(--grayscale-300)]',
        'hover:shadow-none hover:border-[var(--tertiary-color-2)] dark:hover:border-[var(--tertiary-color-2)]',
        'active:bg-[var(--tertiary-color-2)] active:text-[var(--white-color)] dark:active:bg-[var(--tertiary-color-2)]',
        'disabled:border-[var(--grayscale-100)] dark:disabled:border-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-200)] disabled:bg-[var(--grayscale-100)]',
        'dark:disabled:bg-[var(--grayscale-300)] dark:disabled:text-[var(--grayscale-200)]',
        'disabled:shadow-none',
      ],
      tertiaryShadow3: [
        'border border-solid border-[var(--white-color)] dark:border-[var(--grayscale-400)]',
        'bg-[var(--white-color)] dark:bg-[var(--grayscale-400)]',
        'text-[var(--tertiary-color-3)]',
        'shadow-md shadow-[var(--grayscale-200)] dark:shadow-[var(--grayscale-300)]',
        'hover:shadow-none hover:border-[var(--tertiary-color-3)] dark:hover:border-[var(--tertiary-color-2)]',
        'active:bg-[var(--tertiary-color-3)] active:text-[var(--white-color)] dark:active:bg-[var(--tertiary-color-2)]',
        'disabled:border-[var(--grayscale-100)] dark:disabled:border-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-200)] disabled:bg-[var(--grayscale-100)]',
        'dark:disabled:bg-[var(--grayscale-300)] dark:disabled:text-[var(--grayscale-200)]',
        'disabled:shadow-none',
      ],
      supportPastelShadow2: [
        'border border-solid border-[var(--white-color)] dark:border-[var(--grayscale-400)]',
        'bg-[var(--white-color)] dark:bg-[var(--grayscale-400)]',
        'text-[var(--support-pastel-color-2)]',
        'shadow-md shadow-[var(--grayscale-200)] dark:shadow-[var(--grayscale-300)]',
        'hover:shadow-none hover:border-[var(--support-pastel-color-2)] dark:hover:border-[var(--support-pastel-color-2)]',
        'active:bg-[var(--support-pastel-color-2)] active:text-[var(--white-color)] dark:active:bg-[var(--support-pastel-color-2)]',
        'disabled:border-[var(--grayscale-100)] dark:disabled:border-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-200)] disabled:bg-[var(--grayscale-100)]',
        'dark:disabled:bg-[var(--grayscale-300)] dark:disabled:text-[var(--grayscale-200)]',
        'disabled:shadow-none',
      ],
      grayShadow: [
        'border border-solid border-[var(--white-color)] dark:border-[var(--grayscale-400)]',
        'bg-[var(--white-color)] dark:bg-[var(--grayscale-400)]',
        'text-[var(--grayscale-200)]',
        'shadow-md shadow-[var(--grayscale-200)] dark:shadow-[var(--grayscale-300)]',
        'hover:shadow-none hover:border-[var(--grayscale-200)] dark:hover:border-[var(--grayscale-200)]',
        'active:bg-[var(--grayscale-200)] active:text-[var(--white-color)] dark:active:bg-[var(--grayscale-200)]',
        'disabled:border-[var(--grayscale-100)] dark:disabled:border-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-200)] disabled:bg-[var(--grayscale-100)]',
        'dark:disabled:bg-[var(--grayscale-300)] dark:disabled:text-[var(--grayscale-200)]',
        'disabled:shadow-none',
      ],
      successShadow: [
        'border border-solid border-[var(--white-color)] dark:border-[var(--grayscale-400)]',
        'bg-[var(--white-color)] dark:bg-[var(--grayscale-400)]',
        'text-[var(--success-color)]',
        'shadow-md shadow-[var(--grayscale-200)] dark:shadow-[var(--grayscale-300)]',
        'hover:shadow-none hover:border-[var(--success-color)] dark:hover:border-[var(--success-color)]',
        'active:bg-[var(--success-color)] active:text-[var(--white-color)] dark:active:bg-[var(--success-color)]',
        'disabled:border-[var(--grayscale-100)] dark:disabled:border-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-200)] disabled:bg-[var(--grayscale-100)]',
        'dark:disabled:bg-[var(--grayscale-300)] dark:disabled:text-[var(--grayscale-200)]',
        'disabled:shadow-none',
      ],
      dangerShadow: [
        'border border-solid border-[var(--white-color)] dark:border-[var(--grayscale-400)]',
        'bg-[var(--white-color)] dark:bg-[var(--grayscale-400)]',
        'text-[var(--danger-color)]',
        'shadow-md shadow-[var(--grayscale-200)] dark:shadow-[var(--grayscale-300)]',
        'hover:shadow-none hover:border-[var(--danger-color)] dark:hover:border-[var(--danger-color)]',
        'active:bg-[var(--danger-color)] active:text-[var(--white-color)] dark:active:bg-[var(--danger-color)]',
        'disabled:border-[var(--grayscale-100)] dark:disabled:border-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-200)] disabled:bg-[var(--grayscale-100)]',
        'dark:disabled:bg-[var(--grayscale-300)] dark:disabled:text-[var(--grayscale-200)]',
        'disabled:shadow-none',
      ],
      warningShadow: [
        'border border-solid border-[var(--white-color)] dark:border-[var(--grayscale-400)]',
        'bg-[var(--white-color)] dark:bg-[var(--grayscale-400)]',
        'text-[var(--warning-color)]',
        'shadow-md shadow-[var(--grayscale-200)] dark:shadow-[var(--grayscale-300)]',
        'hover:shadow-none hover:border-[var(--warning-color)] dark:hover:border-[var(--warning-color)]',
        'active:bg-[var(--warning-color)] active:text-[var(--white-color)] dark:active:bg-[var(--warning-color)]',
        'disabled:border-[var(--grayscale-100)] dark:disabled:border-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-200)] disabled:bg-[var(--grayscale-100)]',
        'dark:disabled:bg-[var(--grayscale-300)] dark:disabled:text-[var(--grayscale-200)]',
        'disabled:shadow-none',
      ],
      darkShadow: [
        'border border-solid border-[var(--white-color)] dark:border-[var(--white-color)]',
        'bg-[var(--white-color)] dark:bg-[var(--dark-color)]',
        'text-[var(--dark-color)] dark:text-[var(--white-color)]',
        'shadow-md shadow-[var(--grayscale-200)] dark:shadow-[var(--grayscale-300)]',
        'hover:shadow-none hover:border-[var(--dark-color)] dark:hover:border-[var(--white-color)]',
        'active:bg-[var(--dark-color)] active:text-[var(--white-color)] dark:active:text-[var(--dark-color)]',
        'dark:active:bg-[var(--white-color)]',
        'disabled:border-[var(--grayscale-100)] dark:disabled:border-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-200)] disabled:bg-[var(--grayscale-100)]',
        'dark:disabled:bg-[var(--grayscale-300)] dark:disabled:text-[var(--grayscale-200)]',
        'disabled:shadow-none',
      ],
      whiteShadow: [
        'border border-solid border-[var(--dark-color)] dark:border-[var(--white)]',
        'bg-[var(--dark-color)] dark:bg-[var(--white-color)]',
        'text-[var(--white-color)] dark:text-[var(--dark-color)]',
        'shadow-md shadow-[var(--grayscale-200)] dark:shadow-[var(--grayscale-300)]',
        'hover:shadow-none hover:border-[var(--white-color)] dark:hover:border-[var(--dark-color)]',
        'active:bg-[var(--white-color)] active:text-[var(--dark-color)] dark:active:text-[var(--white-color)]',
        'dark:active:bg-[var(--dark-color)]',
        'disabled:border-[var(--grayscale-100)] dark:disabled:border-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-200)] disabled:bg-[var(--grayscale-100)]',
        'dark:disabled:bg-[var(--grayscale-300)] dark:disabled:text-[var(--grayscale-200)]',
        'disabled:shadow-none',
      ],

      // Special themes
      outlinePrimaryDark: [
        'bg-none text-[var(--primary-color)]',
        'border border-solid border-[var(--grayscale-100)] dark:border-[var(--grayscale-300)]',
        'hover:border-[var(--primary-color)] hover:bg-[var(--primary-color)] hover:text-[var(--white-color)]',
        'dark:hover:border-[var(--primary-color)]',
        'active:bg-[var(--dark-color)] active:border-[var(--dark-color)] active:text-[var(--white-color)]',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
      ],
      linkGrayDark: [
        'bg-none text-[var(--grayscale-200)] border border-solid border-transparent',
        'hover:text-[var(--dark-color)] hover:border-[var(--gray-color)] hover:bg-[var(--gray-color)]',
        'dark:hover:text-[var(--grayscale-200)] dark:hover:border-[var(--grayscale-400)] dark:hover:bg-[var(--grayscale-400)]',
        'active:border-[var(--grayscale-100)] active:bg-[var(--grayscale-100)]',
        'dark:active:border-[var(--grayscale-300)] dark:active:bg-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
        'outline-0',
      ],
      linkGrayPrimary: [
        'bg-none text-[var(--grayscale-200)]',
        'hover:text-[var(--primary-color)] dark:hover:text-[var(--primary-color)]',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
        'outline-0',
      ],
      grayFlatPrimary: [
        'bg-none text-[var(--grayscale-200)] border border-solid border-transparent',
        'hover:bg-[var(--gray-color)] dark:hover:bg-[var(--grayscale-400)]',
        'hover:border-[var(--gray-color)] dark:hover:border-[var(--grayscale-400)]',
        'active:text-[var(--primary-color)]',
        'dark:active:text-[var(--primary-color)]',
        'disabled:text-[var(--grayscale-100)]',
        'dark:disabled:text-[var(--grayscale-300)]',
      ],
      graySuccess100: [
        'bg-none text-[var(--grayscale-200)]',
        'bg-[var(--gray-color)] dark:bg-[var(--grayscale-400)]',
        'hover:bg-[var(--success-color-100)]',
        'border border-solid border-[var(--gray-color)] hover:border-[var(--success-color-100)]',
        'active:bg-[var(--success-color)] active:text-[var(--white-color)] active:border-[var(--success-color)]',
        'dark:hover:bg-[var(--success-color-100)] dark:hover:text-[var(--grayscale-200)]',
        'dark:active:bg-[var(--success-color)] dark:active:text-[var(--white-color)] dark:active:border-[var(--success-color)]',
        'dark:border-[var(--grayscale-400)] dark:hover:border-[var(--success-color-100)]',
        'disabled:border-[var(--grayscale-100)] dark:disabled:border-[var(--grayscale-300)]',
        'disabled:text-[var(--grayscale-200)] disabled:bg-[var(--grayscale-100)] dark:disabled:bg-[var(--grayscale-300)]',
      ],
    },
    size: {
      xs: 'p-0.5 text-xs',
      sm: 'px-3 py-2 text-sm',
      md: 'px-4 py-3 text-base',
      lg: 'px-5 py-4 text-lg',
      xl: 'px-6 py-5 text-lg',
    },
  },
});

export const selectContentVariants = tv({
  base: [
    'rounded-md animate-fade-in-down shadow-lg overflow-hidden',
    '[&_.au-item:last-child]:mb-0',
  ],
  variants: {
    theme: {
      white: [
        'bg-[var(--gray-color)]',
        '[&_.au-item]:bg-[var(--white-color)] [&_.au-item]:text-[var(--grayscale-200)]',
        '[&_.au-item[data-highlighted]]:bg-[var(--gray-color)]',
        '[&_.au-item[data-disabled]]:text-[var(--grayscale-100)]',
        '[&_.au-item[data-disabled]]:my-0',
        '[&_.au-select-separator]:bg-[var(--white-color)]',
        '[&_.au-select-label]:bg-[var(--white-color)] [&_.au-select-label]:text-[var(--grayscale-200)]',

        'dark:bg-[var(--grayscale-300)]',
        'dark:[&_.au-item]:bg-[var(--grayscale-400)] dark:[&_.au-item]:text-[var(--grayscale-100)]',
        'dark:[&_.au-item[data-highlighted]]:bg-[var(--dark-color)]',
        'dark:[&_.au-item[data-disabled]]:text-[var(--grayscale-100)] dark:[&_.au-item[data-disabled]]:opacity-80',
        'dark:[&_.au-item[data-disabled]]:bg-[var(--grayscale-300)]',
        'dark:[&_.au-item[data-disabled]]:my-0',
        'dark:[&_.au-select-separator]:bg-[var(--grayscale-400)]',
        'dark:[&_.au-select-label]:bg-[var(--grayscale-400)] dark:[&_.au-select-label]:text-[var(--grayscale-100)]',
      ],
      dark: [
        'bg-[var(--grayscale-300)]',
        '[&_.au-item]:bg-[var(--grayscale-400)] [&_.au-item]:text-[var(--grayscale-100)]',
        '[&_.au-item[data-highlighted]]:bg-[var(--dark-color)]',
        '[&_.au-item[data-disabled]]:text-[var(--grayscale-100)] [&_.au-item[data-disabled]]:opacity-80',
        '[&_.au-item[data-disabled]]:bg-[var(--grayscale-300)]',
        '[&_.au-item[data-disabled]]:my-0',
        '[&_.au-select-separator]:bg-[var(--grayscale-400)]',
        '[&_.au-select-label]:bg-[var(--grayscale-400)] [&_.au-select-label]:text-[var(--grayscale-100)]',

        'dark:bg-[var(--gray-color)]',
        'dark:[&_.au-item]:bg-[var(--white-color)] dark:[&_.au-item]:text-[var(--grayscale-200)]',
        'dark:[&_.au-item[data-highlighted]]:bg-[var(--gray-color)]',
        'dark:[&_.au-item[data-disabled]]:text-[var(--grayscale-100)] dark:[&_.au-item[data-disabled]]:opacity-100',
        'dark:[&_.au-item[data-disabled]]:bg-[var(--white-color)]',
        'dark:[&_.au-item[data-disabled]]:my-0',
        'dark:[&_.au-select-separator]:bg-[var(--white-color)]',
        'dark:[&_.au-select-label]:bg-[var(--white-color)] dark:[&_.au-select-label]:text-[var(--grayscale-200)]',
      ],
    },
  },
});
